force_update:
  description: Force all entities to update their status

action_request:
  description: Sends an action request to the dobiss NXT server
  fields:
    address:
      description: 'VERPLICHT, adres van de module of het NXT actie adres (>200)'
      example: 1
    channel:
      description: VERPLICHT, module uitgang (start bij 0) of NXT uitgang nummer (start op 1),
      example: 1
    action:
      description: VERPLICHT, actie id (0 = uit, 1 = aan, 2 = schakelen) // zie lijst van acties
      example: 2
    option1:
      description: 'dimmer: waarde (0-100) / audio: volume (0-100) / temperatuur: stel temperatuur in of kalender'
      example: 50
    option2:
      description: 'dimmer: soft start/stop (0-254) / audio: bron / temperatuur: periode'
      example: 50

# from the Dobiss API info
# blijkbaar is voor temp, option1 = (target-5)*10
#{
#     "address"   : VERPLICHT, adres van de module of het NXT actie adres (>200),
#     "channel"   : VERPLICHT, module uitgang (start bij 0) of NXT uitgang nummer (start op 1),
#     "action"    : VERPLICHT, actie id (0 = uit, 1 = aan, 2 = schakelen) // zie lijst van acties
#     "option1"   : dimmer: waarde (0-100) / audio: volume (0-100) / temperatuur: stel temperatuur in of kalender
#     "option2"   : dimmer: soft start/stop (0-254) / audio: bron / temperatuur: periode
#     "delayon"   :
#     	{
#     	   "value" : 0-120,
#           "unit"  : "s","min"
#        }
#     "delayoff"  :
#        {
#           "value" : 0-120,
#           "unit"  : "s","min"
#        }
#     "condition" :
#        {
#           "id"    : ID van de logische conditie die nagekeken moet worden voor de uitvoering,
#           "operator": 'true' or 'false'
#     }
#}

status_request:
  description: Sends a status request to the dobiss NXT server
  fields:
    address:
      description: OPTIONEEL, adres van de module of het NXT actie adres (>200)
      example: 1
    channel:
      description: OPTIONEEL, module uitgang (start bij 0) of NXT uitgang nummer (start op 1)
      example: 1

# from the Dobiss API info
#{
#     "address"   : OPTIONEEL, adres van de module of het NXT actie adres (>200),
#     "channel"   : OPTIONEEL, module uitgang (start bij 0) of NXT uitgang nummer (start op 1)
#}
